set nocompatible    " disable backward compatibility with Vi

call plug#begin('~/.config/vim/plugged')
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

Plug 'mattn/emmet-vim'

Plug 'junegunn/vim-easy-align'

Plug 'vim-airline/vim-airline'

Plug 'vim-airline/vim-airline-themes'

Plug 'tpope/vim-fugitive'

Plug 'tpope/vim-surround'

Plug 'sheerun/vim-polyglot'

Plug 'bronson/vim-trailing-whitespace'

Plug 'zenbro/mirror.vim'

Plug 'scrooloose/nerdtree'

Plug 'jmcantrell/vim-virtualenv'

Plug 'bling/vim-bufferline'

" Initialize plugin system
call plug#end()

set nu
set incsearch

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" NerdTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Fix 'No end of new line' problem
set binary
set noeol

" Airline Configuration
"let g:airline_powerline_fonts = 1
"
" Bufferline Configuration
let g:bufferline_active_buffer_left = ''
let g:bufferline_active_buffer_right = ''

" Coc Configuration
source $HOME/.config/coc/coc-config.vim
