#theme = "slick"
#theme = "solarized-dark"
#theme = "solarized-light"
#theme = "modern"
theme = "plain"
#theme = "bad-wolf"
#theme = "gruvbox-light"
#theme = "gruvbox-dark"
icons = "awesome"


#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"

#[[block]]
#block = "backlight"
#device = "intel_backlight"
#step_width = 5

[[block]]
block = "net"
device = "ens1"
speed_down = true
speed_up = true
ssid = false
interval = 5

[[block]]
block = "net"
device = "wlp61s0"
speed_down = false
speed_up = false
ssid = true
interval = 5

[[block]]
block = "memory"
#format_mem = "{Mug}GB/{MTg}GB"
format_mem = "{Mug}GB"
format_swap = "{SUg}GB/{STg}GB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
#format = "%a %d/%m %R"
format = "%m/%d %R"
